[package]
name = "lidar"
version = "0.1.0"
authors = ["Damien Espitallier <damien.espitallier@gmail.com>"]
edition = "2018"

[dependencies]
rppal = "0.11.2"
canars = { path = "../canars" }
dsdl = { path = "../dsdl" }
log = "0.4.6"
pretty_env_logger = "0.3.0"
crossbeam-channel = "0.3.8"
